### ISSUE TITLE
Pretty format for complex nix-shell inputs

### ISSUE THREAD

**Issue by dmadisetti** [haslersn/any-nix-shell#16] opened 2022-06-09 15:07 UTC
Example:

`nix-shell -p 'python38.withPackages(ps: with ps; [ openpyxl pandas pystache jupyter ])'`

creates a really messy terminal line:

```bash
$ »                  [ ]) jupyter openpyxl pandas ps; pystache python38.withPackages(ps: with
                                                      ^
                                                      |
from any shell ----------------------------------------
```

**Comment by haslersn** [comment] 2022-12-10 10:32
Duplicate of #1

**Closed by haslersn** 2022-12-10 10:32 UTC
